# SPDX-FileCopyrightText: 2026 spark contributors <https://github.com/ash-project/spark/graphs.contributors>
#
# SPDX-License-Identifier: MIT

defmodule Spark.CheatSheetTest do
  use ExUnit.Case, async: true

  alias Spark.CheatSheet

  defmodule FakeEntityTarget do
    @moduledoc false
    def hello, do: :world
  end

  defmodule FakeEntity do
    defstruct [
      :name,
      :describe,
      :schema,
      :args,
      :entities,
      :examples,
      :hide,
      :auto_set_fields,
      :target
    ]
  end

  defmodule FakeSection do
    defstruct [
      :name,
      :describe,
      :schema,
      :examples,
      :entities,
      :sections,
      :imports
    ]
  end

  defmodule FakeDsl do
    @moduledoc false

    def sections do
      [
        %FakeSection{
          name: :root,
          describe: "Root section",
          schema: [opt: [type: :atom, doc: "an option"]],
          examples: ["root()"],
          imports: [Some.Imported.Module],
          entities: [sample_entity()],
          sections: [nested_section()]
        }
      ]
    end

    def dsl_patches do
      [
        %Spark.Dsl.Patch.AddEntity{
          section_path: [:root],
          entity: patched_entity()
        }
      ]
    end

    defp nested_section do
      %FakeSection{
        name: :nested,
        describe: "Nested section",
        schema: [flag: [type: :boolean, doc: "nested flag"]],
        examples: ["nested true"],
        imports: [Other.Import],
        entities: [nested_entity()],
        sections: []
      }
    end

    defp sample_entity do
      %FakeEntity{
        name: :sample,
        describe: "Sample entity",
        schema: [value: [type: :integer, doc: "value"]],
        args: [:value],
        hide: [:hidden_opt],
        auto_set_fields: [auto: 10],
        examples: ["sample 10"],
        entities: [{:children, [child_entity()]}],
        target: FakeEntityTarget
      }
    end

    defp child_entity do
      %FakeEntity{
        name: :child,
        describe: "Child entity",
        schema: [child_val: [type: :string, doc: "child"]],
        args: [:child_val],
        hide: [],
        auto_set_fields: [],
        examples: ["child \"ok\""],
        entities: [],
        target: FakeEntityTarget
      }
    end

    defp nested_entity do
      %FakeEntity{
        name: :nested_entity,
        describe: "Nested entity",
        schema: [x: [type: :atom, doc: "x"]],
        args: [:x],
        hide: [],
        auto_set_fields: [],
        examples: ["nested_entity :ok"],
        entities: [],
        target: FakeEntityTarget
      }
    end

    defp patched_entity do
      %FakeEntity{
        name: :patched,
        describe: "Patched entity",
        schema: [patched: [type: :string, doc: "patched"]],
        args: [:patched],
        hide: [],
        auto_set_fields: [],
        examples: ["patched \"yes\""],
        entities: [],
        target: FakeEntityTarget
      }
    end
  end

  describe "cheat_sheet/1" do
    test "generates a full markdown cheat sheet including patches" do
      expected_result = """
      <!--\r
      This file was generated by Spark. Do not edit it by hand.\r
      -->\r
      # Spark.CheatSheetTest.FakeDsl\r\n\r\n\r\n\r
      ## root\r
      Root section\r\n\r
      ### Nested DSLs\r
       * [nested](#root-nested)
         * nested_entity
       * [sample](#root-sample)
         * child\r\n\r\n\r
      ### Examples\r
      ```\r
      root()\r
      ```\r\n\r\n\r\n\r\n
      ### Options\r\n\r
      | Name | Type | Default | Docs |\r
      |------|------|---------|------|\r
      | [`opt`](#root-opt){: #root-opt } | `atom` |  | an option |\r\n\r\n\r
      ### root.nested\r
      Nested section\r\n\r
      ### Nested DSLs\r
       * [nested_entity](#root-nested-nested_entity)\r\n\r\n\r
      ### Examples\r
      ```\r
      nested true\r
      ```\r\n\r\n\r\n\r\n
      ### Options\r\n\r
      | Name | Type | Default | Docs |\r
      |------|------|---------|------|\r
      | [`flag`](#root-nested-flag){: #root-nested-flag } | `boolean` |  | nested flag |\r\n\r\n\r\n\r
      ### root.nested.nested_entity\r
      ```elixir\r
      nested_entity x\r
      ```\r\n\r\n\r
      Nested entity\r\n\r\n\r\n\r
      ### Examples\r
      ```\r
      nested_entity :ok\r
      ```\r\n\r\n\r\n\r
      ### Arguments\r\n\r
      | Name | Type | Default | Docs |\r
      |------|------|---------|------|\r
      | [`x`](#root-nested-nested_entity-x){: #root-nested-nested_entity-x } | `atom` |  | x |\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r
      ### root.sample\r
      ```elixir\r
      sample value\r
      ```\r\n\r\n\r
      Sample entity\r\n\r
      ### Nested DSLs\r
       * [child](#root-sample-child)\r\n\r\n\r
      ### Examples\r
      ```\r
      sample 10\r
      ```\r\n\r\n\r\n\r
      ### Arguments\r\n\r
      | Name | Type | Default | Docs |\r
      |------|------|---------|------|\r
      | [`value`](#root-sample-value){: #root-sample-value } | `integer` |  | value |\n\r\n\r\n\r
      ### root.sample.child\r
      ```elixir\r
      child child_val\r
      ```\r\n\r\n\r
      Child entity\r\n\r\n\r\n\r
      ### Examples\r
      ```\r
      child \"ok\"\r
      ```\r\n\r\n\r\n\r
      ### Arguments\r\n\r
      | Name | Type | Default | Docs |\r
      |------|------|---------|------|\r
      | [`child_val`](#root-sample-child-child_val){: #root-sample-child-child_val } | `String.t` |  | child |\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n
      ### root.patched\r
      ```elixir\r
      patched patched\r
      ```\r\n\r\n\r
      Patched entity\r\n\r\n\r\n\r
      ### Examples\r
      ```\r
      patched \"yes\"\r
      ```\r\n\r\n\r\n\r
      ### Arguments\r\n\r
      | Name | Type | Default | Docs |\r
      |------|------|---------|------|\r
      | [`patched`](#root-patched-patched){: #root-patched-patched } | `String.t` |  | patched |\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r
      <style type=\"text/css\">.spark-required::after { content: \"*\"; color: red !important; }</style>\r
      """

      md = CheatSheet.cheat_sheet(FakeDsl)

      assert md == expected_result
    end

    test "preserves code blocks in section and entity descriptions verbatim" do
      defmodule CodeDsl do
        def sections do
          [
            %FakeSection{
              name: :root,
              describe: """
              Root description

              ```python
              def fibonacci(n):
                  if n <= 0:
                      return []
                  elif n == 1:
                      return [0]
                  elif n == 2:
                      return [0, 1]

                  seq = [0, 1]
                  for i in range(2, n):
                      next_value = seq[i-1] + seq[i-2]
                      seq.append(next_value)
                  return seq

              print(fibonacci(10))
              ```

              After.
              """,
              schema: [],
              examples: [],
              imports: [],
              entities: [
                %FakeEntity{
                  name: :sample,
                  describe: """
                  some desc but with code example below
                  ```elixir
                  defmodule MathUtils do
                    @moduledoc \"\"\"
                    Utility functions for math operations
                    \"\"\"

                    # Compute factorial recursively
                    def factorial(0), do: 1
                    def factorial(n) when n > 0 do
                      n * factorial(n - 1)
                    end

                    # Compute the nth Fibonacci number
                    def fibonacci(0), do: 0
                    def fibonacci(1), do: 1
                    def fibonacci(n) when n > 1 do
                      fibonacci(n - 1) + fibonacci(n - 2)
                    end
                  end

                  IO.puts("Factorial of 5: \#{MathUtils.factorial(5)}")
                  IO.puts("Fibonacci of 10: \#{MathUtils.fibonacci(10)}")
                  ```

                  After code block
                  """,
                  schema: [],
                  args: [],
                  hide: [],
                  auto_set_fields: [],
                  examples: [],
                  entities: [],
                  target: EntityTarget
                }
              ],
              sections: []
            }
          ]
        end

        def dsl_patches, do: []
      end

      md = CheatSheet.cheat_sheet(CodeDsl)

      # Section code block must be preserved EXACTLY, including indentations
      assert md =~ """
             Root description

             ```python
             def fibonacci(n):
                 if n <= 0:
                     return []
                 elif n == 1:
                     return [0]
                 elif n == 2:
                     return [0, 1]

                 seq = [0, 1]
                 for i in range(2, n):
                     next_value = seq[i-1] + seq[i-2]
                     seq.append(next_value)
                 return seq

             print(fibonacci(10))
             ```

             After.
             """

      assert md =~ """
             some desc but with code example below
             ```elixir
             defmodule MathUtils do
               @moduledoc \"\"\"
               Utility functions for math operations
               \"\"\"

               # Compute factorial recursively
               def factorial(0), do: 1
               def factorial(n) when n > 0 do
                 n * factorial(n - 1)
               end

               # Compute the nth Fibonacci number
               def fibonacci(0), do: 0
               def fibonacci(1), do: 1
               def fibonacci(n) when n > 1 do
                 fibonacci(n - 1) + fibonacci(n - 2)
               end
             end

             IO.puts(\"Factorial of 5: \#{MathUtils.factorial(5)}\")
             IO.puts(\"Fibonacci of 10: \#{MathUtils.fibonacci(10)}\")
             ```

             After code block
             """
    end
  end

  describe "section_cheat_sheet/2" do
    test "renders section, options, examples and nested entities" do
      expected_result = """
      ## root\r
      Root section\r\n\r
      ### Nested DSLs\r
       * [nested](#root-nested)
         * nested_entity
       * [sample](#root-sample)
         * child\r\n\r\n\r
      ### Examples\r
      ```\r
      root()\r
      ```\r\n\r\n\r\n\r\n
      ### Options\r\n\r
      | Name | Type | Default | Docs |\r
      |------|------|---------|------|\r
      | [`opt`](#root-opt){: #root-opt } | `atom` |  | an option |\r\n\r\n\r
      ### root.nested\r
      Nested section\r\n\r
      ### Nested DSLs\r
       * [nested_entity](#root-nested-nested_entity)\r\n\r\n\r
      ### Examples\r
      ```\r
      nested true\r
      ```\r\n\r\n\r\n\r\n
      ### Options\r\n\r
      | Name | Type | Default | Docs |\r
      |------|------|---------|------|\r
      | [`flag`](#root-nested-flag){: #root-nested-flag } | `boolean` |  | nested flag |\r\n\r\n\r\n\r
      ### root.nested.nested_entity\r
      ```elixir\r
      nested_entity x\r
      ```\r\n\r\n\r
      Nested entity\r\n\r\n\r\n\r
      ### Examples\r
      ```\r
      nested_entity :ok\r
      ```\r\n\r\n\r\n\r
      ### Arguments\r\n\r
      | Name | Type | Default | Docs |\r
      |------|------|---------|------|\r
      | [`x`](#root-nested-nested_entity-x){: #root-nested-nested_entity-x } | `atom` |  | x |\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r
      ### root.sample\r
      ```elixir\r
      sample value\r
      ```\r\n\r\n\r
      Sample entity\r\n\r
      ### Nested DSLs\r
       * [child](#root-sample-child)\r\n\r\n\r
      ### Examples\r
      ```\r
      sample 10\r
      ```\r\n\r\n\r\n\r
      ### Arguments\r\n\r
      | Name | Type | Default | Docs |\r
      |------|------|---------|------|\r
      | [`value`](#root-sample-value){: #root-sample-value } | `integer` |  | value |\n\r\n\r\n\r
      ### root.sample.child\r
      ```elixir\r
      child child_val\r
      ```\r\n\r\n\r
      Child entity\r\n\r\n\r\n\r
      ### Examples\r
      ```\r
      child \"ok\"\r
      ```\r\n\r\n\r\n\r
      ### Arguments\r\n\r
      | Name | Type | Default | Docs |\r
      |------|------|---------|------|\r
      | [`child_val`](#root-sample-child-child_val){: #root-sample-child-child_val } | `String.t` |  | child |\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r
      """

      section = hd(FakeDsl.sections())
      md = CheatSheet.section_cheat_sheet(section)

      assert md == expected_result
    end
  end

  describe "doc/2" do
    test "generates markdown documentation for DSL" do
      expected_result = """
      ## root\n
      Root section\r\n\r
       * [sample](#module-sample)
         * child
       * [nested](#module-nested)
         * nested_entity\r\n\r
      Examples:
      ```\r
      root()\r
      ```\r\n\r\n\r
      Imports:\n\n* `Some.Imported.Module`\r\n\r
      ---\r\n\r
      * `:opt` (`t:atom/0`) - an option\n\n\r\n\r
      ### sample\n
      Sample entity\r\n\r
          * child\r\n\r
      Examples:
      ```\r
      sample 10\r
      ```\r\n\r\n\r
      * `:value` (`t:integer/0`) - value\n\n\r\n\r
      ##### child\n
      Child entity\r\n\r\n\r\n\r
      Examples:
      ```\r
      child \"ok\"\r
      ```\r\n\r\n\r
      * `:child_val` (`t:String.t/0`) - child\n\n\r\n\r\n\r\n\r\n\r\n\r
      ### nested\n
      Nested section\r\n\r
       * [nested_entity](#module-nested_entity)\r\n\r
      Examples:
      ```\r
      nested true\r
      ```\r\n\r\n\r
      Imports:\n\n* `Other.Import`\r\n\r
      ---\r\n\r
      * `:flag` (`t:boolean/0`) - nested flag\n\n\r\n\r
      #### nested_entity\n
      Nested entity\r\n\r\n\r\n\r
      Examples:
      ```\r
      nested_entity :ok\r
      ```\r\n\r\n\r
      * `:x` (`t:atom/0`) - x\n\n\r\n\r\n\r\n\r\n\r\n\r\n\r
      """

      md = CheatSheet.doc(FakeDsl.sections())

      assert md == expected_result
    end
  end

  describe "doc_section/2" do
    test "documents section options, examples and entities" do
      expected_result = """
      Root section\r\n\r
       * [sample](#module-sample)
         * child
       * [nested](#module-nested)
         * nested_entity\r\n\r
      Examples:
      ```\r
      root()\r
      ```\r\n\r\n\r
      Imports:\n
      * `Some.Imported.Module`\r\n\r
      ---\r\n\r
      * `:opt` (`t:atom/0`) - an option\n\n\r\n\r
      ### sample\n
      Sample entity\r\n\r
          * child\r\n\r
      Examples:
      ```\r
      sample 10\r
      ```\r\n\r\n\r
      * `:value` (`t:integer/0`) - value\n\n\r\n\r
      ##### child\n
      Child entity\r\n\r\n\r\n\r
      Examples:
      ```\r
      child \"ok\"\r
      ```\r\n\r\n\r
      * `:child_val` (`t:String.t/0`) - child\n\n\r\n\r\n\r\n\r\n\r\n\r
      ### nested\n
      Nested section\r\n\r
       * [nested_entity](#module-nested_entity)\r\n\r
      Examples:
      ```\r
      nested true\r
      ```\r\n\r\n\r
      Imports:\n
      * `Other.Import`\r\n\r
      ---\r\n\r
      * `:flag` (`t:boolean/0`) - nested flag\n\n\r\n\r
      #### nested_entity\n
      Nested entity\r\n\r\n\r\n\r
      Examples:
      ```\r
      nested_entity :ok\r
      ```\r\n\r\n\r
      * `:x` (`t:atom/0`) - x\n\n\r\n\r\n\r\n\r\n\r\n\r\n\r
      """

      section = hd(FakeDsl.sections())
      md = CheatSheet.doc_section(section)

      assert md == expected_result
    end
  end

  describe "doc_entity/2" do
    test "documents entity details" do
      expected_result = """
      Sample entity\r\n\r
        * child\r\n\r
      Examples:
      ```\r
      sample 10\r
      ```\r\n\r\n\r
      * `:value` (`t:integer/0`) - value\n\n\r\n\r
      ### child\n
      Child entity\r\n\r\n\r\n\r
      Examples:
      ```\r
      child \"ok\"\r
      ```\r\n\r\n\r
      * `:child_val` (`t:String.t/0`) - child\n\n\r\n\r\n\r\n\r
      """

      entity = hd(hd(FakeDsl.sections()).entities)
      md = CheatSheet.doc_entity(entity)

      assert md == expected_result
    end
  end

  describe "doc_index/3" do
    test "builds nested table of contents" do
      expected_result = """
       * [root](#module-root)
         * sample
           * child
         * nested
           * nested_entity
      """

      md = CheatSheet.doc_index(FakeDsl.sections())

      assert md == String.replace_suffix(expected_result, "\n", "")
    end
  end
end
